baseURL = "https://hugo-minimal-test-theme-demo.wildtechgarden.ca/"
title = "Hugo Minimal Test Theme Demo"
copyright = "Copyright © 2008–2021 Steve Francia, the Hugo Authors, and Daniel F. Dickinson; all rights reserved. (Heavily modified by Daniel F. Dickinson)"
description = "Demo site for hugoMinimalTestTheme, based on Hugo Themes (basicHugoExample) site"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableGitInfo = true

[author]
  name = "Daniel F. Dickinson"
  email = "contact@danielfdickinson.ca"
  homepage = "https://www.danielfdickinson.ca/"

  [[ author.authors ]]
    name = "Daniel F. Dickinson"
    email = "contact@danielfdickinson.ca"
    homepage = "https://www.danielfdickinson.ca/"

  [[ author.authors ]]
    name = "Steve Francia"
    email = "steve.francia@example.com"

  [[ author.authors ]]
    name = "Hugo Authors"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[module]
     [[module.imports]]
        path = "github.com/danielfdickinson/hugoMinimalTestTheme"

[markup]
  [markup.goldmark]
    [ markup.goldmark.renderer ]
      unsafe = true

[params]
  debugExpandPage = true
  testStylesInclude = true
  debugTableEnvironment = ["production","development"]

[frontmatter]
  lastmod = ["lastmod",":fileModTime",":git","date","publishDate"]
  date = ["date","publishDate","lastmod",":git",":fileModTime"]
  publishDate = ["publishDate","date","lastmod",":git",":fileModTime"]
